/**
 * GENERATED BY `npm run setup:portfolio` AFTER VERIFY + COMPLETE.
 *
 * This is non-secret deployment safety metadata. A fork inherits this file,
 * but its production build remains blocked because the recorded repository
 * identity will not match the fork's provider, CI, or git-origin identity.
 */

import type { OwnerSetupManifest } from './ownerSetupManifest';

export const OWNER_SETUP_MANIFEST: OwnerSetupManifest = {
  schemaVersion: 1,
  setupCompleted: true,
  configuredRepositoryOwner: 'SalAkBuK',
  configuredRepositoryName: 'Systems_Cartography_Portfolio',
  portfolioGithubOwner: 'SalAkBuK'
};
