import * as fs from 'node:fs';
import * as path from 'node:path';
import type { OwnerSetupManifest } from '../src/config/ownerSetupManifest';

export const DEFAULT_OWNER_SETUP_MANIFEST_PATH = path.resolve(
  process.cwd(),
  'src/config/ownerSetup.generated.ts'
);

export function serializeOwnerSetupManifest(manifest: OwnerSetupManifest): string {
  return `/**
 * GENERATED BY \`npm run setup:portfolio\` AFTER VERIFY + COMPLETE.
 *
 * This is non-secret deployment safety metadata. A fork inherits this file,
 * but its production build remains blocked because the recorded repository
 * identity will not match the fork's provider, CI, or git-origin identity.
 */

import type { OwnerSetupManifest } from './ownerSetupManifest';

export const OWNER_SETUP_MANIFEST: OwnerSetupManifest = ${JSON.stringify(manifest, null, 2)};
`;
}

export function writeOwnerSetupManifest(
  manifest: OwnerSetupManifest,
  outputPath = DEFAULT_OWNER_SETUP_MANIFEST_PATH
): void {
  fs.writeFileSync(outputPath, serializeOwnerSetupManifest(manifest), 'utf8');
}
